### ISSUE TITLE
Extension review question

### ISSUE THREAD

**Issue by pr-Mais** [ChatKitty/chatkitty-firebase-extension#1]
Hello! thanks for submitting a new extension to the marketplace.

I was reviewing your extension and would like to ask if it's going to support more features other than just syncing users, for example, sending or syncing chat messages through Firestore?

The reason for the question is that the current ID is a bit short and generic, so in case more features are planned the current ID should be ok, otherwise I think it could be changed to something like `chatkitty-auth-sync`.

**Comment by aerovulpe** [comment]
Hi @pr-Mais,

Thank you for reviewing our extension! Yes, we do plan to support additional features, including syncing chat messages, channels, and more.

Our goal is to seamlessly integrate with Firebase, as our customers widely use it.

I've also submitted a new extension version with the requested secret value changes. We’re excited to share our extension with users on the marketplace.

Best regards,
Aaron

**Comment by pr-Mais** [comment]
Sounds exciting, all the best! Just few nits to solve in the latest version and the extension is good to go.
